[package]
name = "http-client-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "http_client"
crate-type = ["dylib"]

[dependencies]
